---
settings:
  name: XCP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentação do NetApp XCP
    url: "/index.html"
  - title: Notas de versão
    url: "/releasenotes.html"
  - title: Comece a usar o XCP
    entries:
    - title: Saiba mais sobre XCP
      url: "/xcp-index.html"
    - title: Recursos adicionais do XCP NFS
      url: "/xcp-nfs-add-ons.html"
    - title: Funcionalidades não suportadas
      url: "/xcp-unsupported-features.html"
    - title: Configurações compatíveis
      url: "/xcp-supported-configurations.html"
    - title: Portas usadas pelo XCP
      url: "/xcp-ports-used.html"
  - title: Instale o XCP
    entries:
    - title: Prepare-se para a instalação do XCP
      url: "/xcp-install-xcp.html"
    - title: Prepare o Linux para XCP NFS
      url: "/xcp-prepare-linux-for-xcp-nfs.html"
    - title: Prepare o Windows para XCP SMB
      url: "/xcp-prepare-windows-for-xcp-smb.html"
    - title: Preparar análise de ficheiros
      url: "/xcp-prepare-file-analytics.html"
    - title: Instale o XCP NFS
      url: "/xcp-install-xcp-nfs.html"
    - title: Instale o SMB do XCP
      url: "/xcp-install-xcp-smb.html"
    - title: Instale o File Analytics para NFS
      url: "/xcp-install-file-analytics-for-nfs.html"
    - title: Instale o File Analytics para SMB
      url: "/xcp-install-file-analytics-for-smb.html"
  - title: Configure o XCP
    entries:
    - title: Configure o arquivo INI para XCP NFS
      url: "/xcp-configure-the-ini-file-for-xcp-nfs.html"
    - title: Ajuste de desempenho
      url: "/xcp-performance-tuning.html"
    - title: Variável de ambiente
      url: "/xcp-environment-variable.html"
    - title: Configure o conetor POSIX
      url: "/xcp-configure-posix-connector-nfs.html"
    - title: Configure o conetor HDFS
      url: "/xcp-configure-hdfs-connector-nfs.html"
    - title: Configure a escalabilidade horizontal de vários nós
      url: "/xcp-configure-multinode-scaleout-nfs.html"
    - title: Configure o conetor S3
      url: "/xcp-configure-s3-connector-nfs.html"
  - title: Planejar a migração de dados
    entries:
    - title: Visão geral
      url: "/xcp-plan-data-migration.html"
    - title: Planejar a migração de dados NFS
      url: "/xcp-plan-nfs-data-migration.html"
    - title: Planejar a migração de dados SMB
      url: "/xcp-plan-smb-data-migration.html"
    - title: Planear a migração de dados HDFS
      url: "/xcp-plan-hdfs-data-migration.html"
    - title: Planeje usando a análise de arquivos
      entries:
      - title: Planeje sua migração de dados
        url: "/xcp-file-analytics-plan-data-migration.html"
      - title: Acesse o File Analytics
        url: "/xcp-access-file-analytics.html"
      - title: Adicionar servidores de arquivos
        url: "/xcp-add-file-servers.html"
      - title: Execute uma digitalização
        url: "/xcp-run-a-scan.html"
    - title: Filtros
      url: "/xcp-filters.html"
    - title: Log para NFS e SMB (opcional)
      url: "/xcp-logging-for-nfs-and-smb.html"
  - title: Migrar dados
    entries:
    - title: Migrar dados NFS
      url: "/xcp-migrate-data.html"
    - title: Migrar dados SMB
      url: "/xcp-migrate-smb-data.html"
    - title: Migração de fluxos de dados alternativos NTFS para SMB
      entries:
      - title: Migração de fluxos de dados alternativos NTFS para SMB
        url: "/xcp-smb-ads.html"
    - title: Migrar dados HDFS
      url: "/xcp-migrate-hdfs-data.html"
    - title: Execute vários trabalhos XCP no mesmo host
      url: "/xcp-run-multiple-jobs-on-same-host.html"
    - title: Recursos NFS adicionais
      url: "/xcp-migrate-nfs-additional-features.html"
  - title: Solucionar problemas
    entries:
    - title: Solucionar erros de NFS do XCP
      url: "/xcp-troubleshoot-xcp-nfs.html"
    - title: Solucionar erros do XCP SMB
      url: "/xcp-troubleshoot-xcp-smb-errors.html"
    - title: Solucionar erros do XCP File Analytics
      url: "/xcp-troubleshoot-xcp-file-analytics-errors.html"
  - title: Referência da XCP
    entries:
    - title: Visão geral da referência do comando XCP
      url: "/xcp-reference-overview.html"
    - title: Referência do comando NFS
      entries:
      - title: ajuda
        url: "/xcp-nfs-reference-help.html"
      - title: mostrar
        url: "/xcp-nfs-reference-show.html"
      - title: licença
        url: "/xcp-nfs-reference-license.html"
      - title: ativar
        url: "/xcp-nfs-reference-activate.html"
      - title: digitalizar
        url: "/xcp-nfs-reference-scan.html"
      - title: cópia
        url: "/xcp-nfs-reference-copy.html"
      - title: sincronizar
        url: "/xcp-nfs-reference-sync.html"
      - title: retomar
        url: "/xcp-nfs-reference-resume.html"
      - title: verifique
        url: "/xcp-nfs-reference-verify.html"
      - title: chmod
        url: "/xcp-nfs-reference-chmod.html"
      - title: chown
        url: "/xcp-nfs-reference-chown.html"
      - title: despejo de memória
        url: "/xcp-nfs-reference-logdump.html"
      - title: eliminar
        url: "/xcp-nfs-reference-delete.html"
      - title: estimativa
        url: "/xcp-nfs-reference-estimate.html"
      - title: indexdelete
        url: "/xcp-nfs-reference-indexdelete.html"
      - title: isync
        url: "/xcp-nfs-reference-isync.html"
    - title: Referência do comando SMB
      entries:
      - title: ajuda
        url: "/xcp-smb-reference-help.html"
      - title: mostrar
        url: "/xcp-smb-reference-show.html"
      - title: licença
        url: "/xcp-smb-reference-license.html"
      - title: ativar
        url: "/xcp-smb-reference-activate.html"
      - title: digitalizar
        url: "/xcp-smb-reference-scan.html"
      - title: cópia
        url: "/xcp-smb-reference-copy.html"
      - title: sincronizar
        url: "/xcp-smb-reference-sync.html"
      - title: verifique
        url: "/xcp-smb-reference-verify.html"
      - title: configurar
        url: "/xcp-smb-reference-configure.html"
      - title: ouça
        url: "/xcp-smb-reference-listen.html"
    - title: Casos de uso da XCP
      entries:
      - title: Casos de uso da XCP
        url: "/xcp-reference-use-cases.html"
    - title: Registo XCP
      entries:
      - title: Defina a opção logConfig
        url: "/xcp-reference-logging-logconfig.html"
      - title: Defina a opção eventlog
        url: "/xcp-reference-logging-eventlog.html"
      - title: Ative o cliente syslog
        url: "/xcp-reference-logging-syslog.html"
    - title: Registos de eventos XCP
      entries:
      - title: Logs de eventos NFS
        url: "/xcp-reference-event-logs-nfs.html"
      - title: Logs de eventos SMB
        url: "/xcp-reference-event-logs-smb.html"
  - title: Avisos legais
    url: "/legal-notices.html"
