---
sidebar: sidebar 
permalink: xcp-nfs-reference-delete.html 
keywords: netapp, xcp, reference, nfs, command, commands 
summary: Referência do comando XCP NFS 
---
= eliminar
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O comando XCP NFS `delete` exclui tudo em um determinado caminho.

.Sintaxe
[source, cli]
----
xcp delete <NFS export path>
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
[root@localhost ]# /xcp/linux/xcp delete <IP address of destination NFSserver>:/dest_vol

WARNING: You have selected <IP address of destination NFS server>:/dest_vol for
removing data.Data in this path /dest_vol will be deleted.
Are you sure you want to delete (yes/no): yes
Recursively removing data in <IP address of destination NFS server>:/dest_vol ...
31,996 scanned, 5,786 removes, 3 rmdirs, 8.27 MiB in (1.65 MiB/s), 1.52 MiB out (312
KiB/s), 5s
40,324 scanned, 19,829 removes, 22 rmdirs, 12.2 MiB in (799 KiB/s), 3.89 MiB out
(485 KiB/s),10s
54,281 scanned, 32,194 removes, 2,365 rmdirs, 17.0 MiB in (991 KiB/s), 6.15 MiB out
(463 KiB/s),15s
75,869 scanned, 44,903 removes, 4,420 rmdirs, 23.4 MiB in (1.29 MiB/s), 8.60
MiB out (501KiB/s), 20s
85,400 scanned, 59,728 removes, 5,178 rmdirs, 27.8 MiB in (881 KiB/s), 11.1 MiB out
(511 KiB/s),25s
106,391 scanned, 76,229 removes, 6,298 rmdirs, 34.7 MiB in (1.39 MiB/s), 14.0
MiB out (590KiB/s), 30s
122,107 scanned, 93,203 removes, 7,448 rmdirs, 40.9 MiB in (1.24 MiB/s), 16.9
MiB out (606KiB/s), 35s
134,633 scanned, 109,815 removes, 9,011 rmdirs, 46.5 MiB in (1.12 MiB/s), 20.0
MiB out (622KiB/s), 40s
134,633 scanned, 119,858 removes, 9,051 rmdirs, 47.9 MiB in (288 KiB/s), 21.4
MiB out (296KiB/s), 45s
134,633 scanned, 119,858 removes, 9,051 rmdirs, 47.9 MiB in (0/s), 21.4 MiB out (0/s), 50s
134,633 scanned, 121,524 removes, 9,307 rmdirs, 48.2 MiB in (51.7 KiB/s), 21.7
MiB out (49.5KiB/s), 55s
Xcp command : xcp delete <IP address of destination NFS
server>:/dest_vol134,633 scanned, 0 matched, 134,632 delete
items, 0 error
Speed : 48.7 MiB in (869 KiB/s), 22.2 MiB out
(396 KiB/s)Total Time : 57s.
STATUS : PASSED
----
====
A tabela a seguir lista os `delete` parâmetros e sua descrição.

[cols="2*"]
|===
| Parâmetro | Descrição 


| <<nfs_delete_match,eliminar -corresponder >> | Apenas processa os arquivos e diretórios que correspondem ao filtro. 


| <<nfs_delete_force,eliminar -force>> | Elimina sem confirmação. 


| <<nfs_delete_removetopdir,delete -removetopodir>> | Remove o diretório, incluindo diretórios filho. 


| <<nfs_delete_exclude,eliminar -excluir >> | Exclui os arquivos e diretórios que correspondem ao filtro. 


| <<nfs_delete_parallel,eliminar -paralelo >> | Especifica o máximo de processos em lote simultâneos (padrão: 7). 


| <<nfs_delete_preserveatime,delete -preserve-atime>> | Preserva o tempo de acesso do arquivo ou diretório (padrão: False). 


| <<nfs_delete_loglevel,eliminar -loglevel >> | Define o nível de log; os níveis disponíveis são INFO, DEBUG (default: INFO). 


| <<nfs_delete_s3_insecure,eliminar -s3.insecure>> | Fornece a opção de usar HTTP em vez de HTTPS para comunicação de bucket S3. 


| <<nfs_delete_endpoint,eliminar -s3.endpoint >> | Substitui o URL padrão do endpoint do Amazon Web Services (AWS) com o URL especificado para a comunicação de bucket do S3. 


| <<nfs_delete_s3_profile,eliminar -s3.profile >> | Especifica um perfil do arquivo de credenciais da AWS para comunicação de bucket do S3. 


| <<nfs_delete_s3_noverify,eliminar -s3.noverify>> | Substitui a verificação padrão da certificação SSL para comunicação de bucket S3. 
|===


== excluir -match <filter>

Use o `-match <filter>` parâmetro com o `delete` comando para processar apenas os arquivos e diretórios que correspondem ao filtro.

.Sintaxe
[source, cli]
----
xcp delete -match <filter> <NFS export path>
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp delete -match "fnm('XCP_copy_2023-04-25_05.51.28.315997')" 10.101.10.101:/xcp_catalog

Job ID: Job_2023-04-25_06.10.29.637371_delete
WARNING: You have selected 10.101.10.101:/xcp_catalog for removing data. Data in this path
/xcp_catalog will be deleted.
Are you sure you want to delete (yes/no): yes
Recursively removing data in 10.101.10.101:/xcp_catalog ...
Xcp command : xcp delete -match fnm('XCP_copy_2023-04-25_05.51.28.315997')
10.101.10.101:/xcp_catalog
Stats : 209 scanned, 14 matched, 12 removes, 2 rmdirs
Speed : 58.9 KiB in (18.6 KiB/s), 8.25 KiB out (2.60 KiB/s)
Total Time : 3s.
Job ID : Job_2023-04-25_06.10.29.637371_delete
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-25_06.10.29.637371_delete.log
STATUS : PASSED
----
====


== eliminar -force

Use o `-force` parâmetro com o `delete` comando para excluir sem confirmação.

.Sintaxe
[source, cli]
----
xcp delete -force <NFS export path>
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp delete -force
10.101.10.101:/xcp_catalog/catalog/indexes/XCP_copy_2023-04-25_05.53.58.273910

Job ID: Job_2023-04-25_06.11.30.584440_delete
WARNING: You have selected 10.101.10.101:/xcp_catalog/catalog/indexes/XCP_copy_2023-04-
25_05.53.58.273910 for removing data. Data in this path
/xcp_catalog/catalog/indexes/XCP_copy_2023-04-25_05.53.58.273910 will be deleted.
Recursively removing data in 10.101.10.101:/xcp_catalog/catalog/indexes/XCP_copy_2023-04-
25_05.53.58.273910 ...
Xcp command : xcp delete -force 110.101.10.101:/xcp_catalog/catalog/indexes/XCP_copy_2023-04-
25_05.53.58.273910
Stats : 14 scanned, 12 removes, 1 rmdir
Speed : 6.44 KiB in (4.73 KiB/s), 3.59 KiB out (2.64 KiB/s)
Total Time : 1s.
Job ID : Job_2023-04-25_06.11.30.584440_delete
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-25_06.11.30.584440_delete.log
STATUS : PASSED
[root@client-1 linux] #
----
====


== delete -removetopodir

Use o `-removetopdir` parâmetro com o `delete` comando para remover o diretório, incluindo diretórios filho.

.Sintaxe
[source, cli]
----
xcp delete -force -loglevel <name> -removetopdir <NFS export path>
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp delete -force -loglevel DEBUG -removetopdir
10.101.10.101:/temp7/user9

Job ID: Job_2023-04-25_08.03.38.218893_delete
WARNING: You have selected 10.101.10.101:/temp7/user9 for removing data. Data in this path
/temp7/user9 will be deleted.
Recursively removing data in 10.101.10.101:/temp7/user9 ...
50,500 scanned, 16,838 removes, 11.5 MiB in (2.27 MiB/s), 2.70 MiB out (547 KiB/s), 5s
85,595 scanned, 43,016 removes, 21.5 MiB in (1.97 MiB/s), 6.70 MiB out (806 KiB/s), 10s
.
.
.
1.01M scanned, 999,771 removes, 1,925 rmdirs, 324 MiB in (1.42 MiB/s), 153 MiB out (922
KiB/s), 3m6s

Xcp command : xcp delete -force -loglevel DEBUG -removetopdir 10.101.10.101:/temp7/user9
Stats : 1.01M scanned, 1.01M removes, 2,041 rmdirs
Speed : 326 MiB in (1.73 MiB/s), 155 MiB out (842 KiB/s)
Total Time : 3m8s.
Job ID : Job_2023-04-25_08.03.38.218893_delete
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-25_08.03.38.218893_delete.log
STATUS : PASSED
[root@client1 linux]#
----
====


== excluir -excluir <filter>

Use o `-exclude <filter>` parâmetro com o `delete` comando para excluir os arquivos e diretórios que correspondem ao filtro.

.Sintaxe
[source, cli]
----
xcp delete -force -exclude <filter>  <NFS export path>
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp delete -force -exclude "fnm('USER5')" 10.101.10.101:/temp7/user2/

Job ID: Job_2023-04-25_07.54.25.241216_delete
WARNING: You have selected 10.101.10.101:/temp7/user2 for removing data. Data in this path
/temp7/user2 will be deleted.
Recursively removing data in 10.101.10.101:/temp7/user2 ...
29,946 scanned, 1 excluded, 6,492 removes, 977 rmdirs, 7.42 MiB in (1.48 MiB/s), 1.54 MiB out
(316 KiB/s), 5s
Xcp command : xcp delete -force -exclude fnm('USER5') 10.101.10.101:/temp7/user2/
Stats : 29,946 scanned, 1 excluded, 28,160 removes, 1,785 rmdirs
Speed : 10.6 MiB in (1.18 MiB/s), 5.03 MiB out (574 KiB/s)
Total Time : 8s.
Job ID : Job_2023-04-25_07.54.25.241216_delete
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-25_07.54.25.241216_delete.log
STATUS : PASSED
[root@client1 linux]#
----
====


== eliminar -parallel <n>

Use o `-parallel <n>` parâmetro com o `delete` comando para especificar o número máximo de processos em lote simultâneos. O valor padrão é 7.

.Sintaxe
[source, cli]
----
xcp delete -force -parallel <n> -match <filter> <NFS export path>
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp delete -force -parallel 8 -match "fnm('2023-04-25_05.49.26.733160*')" 10.101.10.101:/xcp_catalog/

Job ID: Job_2023-04-25_06.15.27.024987_delete
WARNING: You have selected 10.101.10.101:/xcp_catalog for removing data. Data in this path /xcp_catalog will be deleted.
Recursively removing data in 10.101.10.101:/xcp_catalog ...
Xcp command : xcp delete -force -parallel 8 -match fnm('2023-04-25_05.49.26.733160*')
10.101.10.101:/xcp_catalog/
Stats : 182 scanned, 1 matched, 1 remove
Speed : 50.0 KiB in (115 KiB/s), 5.45 KiB out (12.5 KiB/s)
Total Time : 0s.
Job ID : Job_2023-04-25_06.15.27.024987_delete
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-25_06.15.27.024987_delete.log
STATUS : PASSED
[root@client1 linux]#
----
====


== delete -preserve-atime

Use o `-preserve-atime <preserve-atime>` parâmetro com o `delete` comando para preservar o tempo de acesso de um arquivo ou diretório. O valor padrão é false.

.Sintaxe
[source, cli]
----
xcp delete -force -preserve-atime <NFS export path>
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp delete -force -preserve-atime <IP_address>:/temp7/user2/

Job ID: Job_2023-04-25_07.55.30.972162_delete
WARNING: You have selected <IP_address>:/temp7/user2 for removing data. Data in this path
/temp7/user2 will be deleted.
Recursively removing data in <IP_address>:/temp7/user2 ...
Xcp command : xcp delete -force -preserve-atime <IP_address>:/temp7/user2/
Stats : 256 scanned, 255 rmdirs
Speed : 199 KiB in (108 KiB/s), 75.7 KiB out (41.1 KiB/s)
Total Time : 1s.
Job ID : Job_2023-04-25_07.55.30.972162_delete
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-25_07.55.30.972162_delete.log
STATUS : PASSED
[root@client-1 linux]#
----
====


== delete -loglevel <name>

Use o `-loglevel <name>` parâmetro com o `delete` comando para definir o nível de log; os níveis disponíveis são INFO e DEBUG. O nível padrão é INFO.

.Sintaxe
[source, cli]
----
xcp delete -force -loglevel DEBUG -removetopdir <NFS export path>
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp delete -force -loglevel DEBUG -removetopdir
10.101.10.101:/temp7/user9

Job ID: Job_2023-04-25_08.03.38.218893_delete
WARNING: You have selected 10.101.10.101:/temp7/user9 for removing data. Data in this
path /temp7/user9 will be deleted.
Recursively removing data in 10.101.10.101:/temp7/user9 ...
50,500 scanned, 16,838 removes, 11.5 MiB in (2.27 MiB/s), 2.70 MiB out (547 KiB/s), 5s
85,595 scanned, 43,016 removes, 21.5 MiB in (1.97 MiB/s), 6.70 MiB out (806 KiB/s),
10s
.
.
.
1.01M scanned, 999,771 removes, 1,925 rmdirs, 324 MiB in (1.42 MiB/s), 153 MiB out
(922 KiB/s), 3m6s
Xcp command : xcp delete -force -loglevel DEBUG -removetopdir
10.101.10.101:/temp7/user9
Stats : 1.01M scanned, 1.01M removes, 2,041 rmdirs
Speed : 326 MiB in (1.73 MiB/s), 155 MiB out (842 KiB/s)
Total Time : 3m8s.
Job ID : Job_2023-04-25_08.03.38.218893_delete
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-25_08.03.38.218893_delete.log
STATUS : PASSED
[root@client-1 linux]#
----
====


== eliminar -s3.insecure

Use o `-s3.insecure` parâmetro com o `delete` comando para usar HTTP em vez de HTTPS para comunicação de bucket S3.

.Sintaxe
[source, cli]
----
xcp delete -s3.insecure s3://bucket1
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp delete -s3.insecure s3:// bucket1

Job ID: Job_2023-06-08_08.51.40.849991_delete
WARNING: You have selected s3://bucket1 for removing data. Data in this path //bucket1 will be
deleted.
Are you sure you want to delete (yes/no): yes
Recursively removing data in s3://bucket1 ...
Xcp command : xcp delete -s3.insecure s3://bucket1
Stats : 8 scanned, 6 s3.objects, 6 s3.removed
Speed : 0 in (0/s), 0 out (0/s)
Total Time : 5s.
Job ID : Job_2023-06-08_08.51.40.849991_delete
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-06-08_08.51.40.849991_delete.log
STATUS : PASSED
----
====


== excluir -s3.endpoint <s3_endpoint_url>

Use o `-s3.endpoint <s3_endpoint_url>` parâmetro com o `delete` comando para substituir o URL de endpoint padrão da AWS com um URL especificado para a comunicação de bucket do S3.

.Sintaxe
[source, cli]
----
xcp delete -s3.endpoint https://<endpoint_url>: s3://bucket
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp delete -s3.endpoint https://<endpoint_url>: s3://xcp-testing

Job ID: Job_2023-06-13_11.39.33.042545_delete
WARNING: You have selected s3://xcp-testing for removing data. Data in this path //xcp-testing
will be deleted.
Are you sure you want to delete (yes/no): yes
Recursively removing data in s3://xcp-testing ...
Xcp command : xcp delete -s3.endpoint https://<endpoint_url>: s3://xcp-testing
Stats : 8 scanned, 5 s3.objects, 5 s3.removed
Speed : 0 in (0/s), 0 out (0/s)
Total Time : 4s.
Job ID : Job_2023-06-13_11.39.33.042545_delete
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-06-13_11.39.33.042545_delete.log
STATUS : PASSED
----
====


== eliminar -s3.profile <name>

Use o `s3.profile` parâmetro com o `delete` comando para especificar um perfil do arquivo de credenciais da AWS para comunicação de bucket do S3.

.Sintaxe
[source, cli]
----
xcp delete -s3.profile sg -s3.endpoint https://<endpoint_url>:
s3://bucket
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp delete -s3.profile sg -s3.endpoint https://<endpoint_url>: s3://bucket

Job ID: Job_2023-06-08_08.53.19.059745_delete
WARNING: You have selected s3://bucket for removing data. Data in this path //bucket will be deleted.
Are you sure you want to delete (yes/no): yes
Recursively removing data in s3://bucket ...
1 scanned, 0 in (0/s), 0 out (0/s), 5s
Xcp command : xcp delete -s3.profile sg -s3.endpoint https://<endpoint_url>: s3:/ bucket
Stats : 7 scanned, 5 s3.objects, 5 s3.removed
Speed : 0 in (0/s), 0 out (0/s)
Total Time : 9s.
Job ID : Job_2023-06-08_08.53.19.059745_delete
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-06-08_08.53.19.059745_delete.log
STATUS : PASSED
----
====


== eliminar -s3.noverify

Use o `-s3.noverify` parâmetro com o `delete` comando para substituir a verificação padrão da certificação SSL para comunicação de bucket S3.

.Sintaxe
[source, cli]
----
xcp delete -s3.noverify s3://bucket
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
[root@client-1 linux]# ./xcp delete -s3.noverify s3://bucket1

Job ID: Job_2023-06-13_10.56.19.319076_delete
WARNING: You have selected s3://bucket1 for removing data. Data in this path //bucket1 will be
deleted.
Are you sure you want to delete (yes/no): yes
Recursively removing data in s3://bucket1 ...
2,771 scanned, 0 in (0/s), 0 out (0/s), 5s
9,009 scanned, 9,005 s3.objects, 2,000 s3.removed, 0 in (0/s), 0 out (0/s), 10s
Xcp command : xcp delete -s3.noverify s3://bucket1
Stats : 9,009 scanned, 9,005 s3.objects, 9,005 s3.removed
Speed : 0 in (0/s), 0 out (0/s)
Total Time : 15s.
Job ID : Job_2023-06-13_10.56.19.319076_delete
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-06-13_10.56.19.319076_delete.log
STATUS : PASSED
----
====