---
sidebar: sidebar 
permalink: xcp-nfs-reference-scan.html 
keywords: netapp, xcp, reference, nfs, command, commands 
summary: Referência do comando XCP NFS 
---
= digitalizar
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O comando XCP NFS `scan` verifica recursivamente todo o NFSv3 caminhos exportados de origem e retorna estatísticas de estrutura de arquivos.

A NetApp recomenda que você coloque as montagens de exportação NFS de origem no modo somente leitura durante a operação de digitalização.

.Sintaxe
[source, cli]
----
xcp scan <source_nfs_export_path>
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan <IP address of NFS server>:/

source_vol
source_vol
source_vol/r1.txt
source_vol/USER.1
source_vol/USER.2
source_vol/USER.1/FILE_1
source_vol/USER.1/FILE_2
source_vol/USER.1/FILE_3
source_vol/USER.1/FILE_4
source_vol/USER.1/FILE_5
source_vol/USER.1/file1.txt
source_vol/USER.1/file2.txt
source_vol/USER.1/logfile.txt
source_vol/USER.1/log1.txt
source_vol/USER.2/FILE_1
source_vol/USER.2/FILE_5
source_vol/USER.2/FILE_2
source_vol/USER.2/FILE_3
source_vol/USER.2/FILE_4
Xcp command : xcp scan <IP address of NFS server>:/source vol
----
====
A tabela a seguir lista os `scan` parâmetros e sua descrição.

[cols="2*"]
|===
| Parâmetro | Descrição 


| <<scan_l,digitalização -l>> | Lista os arquivos no formato de saída de listagem longa. 


| <<scan_q,digitalização -q>> | Mostra o número de ficheiros lidos. 


| <<nfs_scan_stats_csv_html,estatísticas de exame>> | Lista os arquivos no formato de relatório estatístico de árvore. 


| <<nfs_scan_stats_csv_html,digitalização -csv>> | Lista os arquivos no formato de relatório CSV de estatísticas de árvore. 


| <<nfs_scan_stats_csv_html,digitalização -html>> | Lista os arquivos no formato de relatório HTML estatístico de árvore. 


| <<scan -não-nomes>> | Exclui nomes de usuários e grupos de listas de arquivos e relatórios. 


| <<nfs_scan_newid,scan -newid >> | Especifica o nome do catálogo para um novo índice. 


| <<nfs_scan_id,scan -id >> | Especifica o nome do catálogo de uma cópia ou índice de digitalização anterior. 


| <<nfs_scan_match,scan -match >> | Apenas processa arquivos e diretórios que correspondem ao filtro. 


| <<nfs_scan_fmt,scan -fmt >> | Apenas processa arquivos e diretórios que correspondem ao formato. 


| <<nfs_scan_du,digitalização -du>> | Resume o uso de espaço de cada diretório, incluindo subdiretórios. 


| <<nfs_scan_md5,scan -md5 >> | Gera somas de verificação nos arquivos e salva as somas de verificação ao indexar (padrão: False). 


| <<nfs_scan_depth,scan -depth >> | Limita a profundidade de pesquisa. 


| <<nfs_scan_dircount,digitalização -dircount [k]> | Especifica o tamanho da solicitação ao ler diretórios. 


| <<nfs_scan_edupe,digitalização -edupe>> | Inclui a estimativa de deduplicação nos relatórios. 


| <<nfs_scan_bs,scan -bs [k]> | Especifica o tamanho do bloco de leitura/gravação para varreduras que leem dados usando `-md5` ou `-edupe` (padrão: 64K). 


| <<nfs_scan_parallel,digitalização -paralela >> | Especifica o número máximo de processos em lote simultâneos (padrão: 7). 


| <<nfs_scan_noid,Scan -noid>> | Desativa a criação de um índice padrão (default: False). 


| <<nfs_scan_subdir,scan -subdir-namentos>> | Recupera os nomes dos subdiretórios de nível superior em um diretório. 


| <<digitalização -preservar-tempo>> | Restaura todos os arquivos para a última data acessada na origem. 


| <<digitalização -s3.insecure>> | Fornece a opção de usar HTTP em vez de HTTPS para comunicação de bucket S3. 


| <<nfs_scan_endpoint,scan -s3.endpoint >> | Substitui o URL padrão do endpoint do Amazon Web Services (AWS) com o URL especificado para a comunicação de bucket do S3. 


| <<nfs_scan_s3_profile,digitalização -s3.profile >> | Especifica um perfil do arquivo de credenciais da AWS para comunicação de bucket do S3. 


| <<digitalização -s3.noverify>> | Substitui a verificação padrão da certificação SSL para comunicação de bucket S3. 
|===


== digitalização -l

Use o `-l` parâmetro com o `scan` comando para listar arquivos no formato de saída de listagem longa.

.Sintaxe
[source, cli]
----
xcp scan -l <ip_address_or_hostname>:/source_vol
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
root@localhost linux]# ./xcp scan -l <IP address or hostname of NFSserver>:/source_vol

drwxr-xr-x --- root root 4KiB 4KiB 6s source_vol
drwxr-xr-x --- root root 4KiB 4KiB 42s source_vol/USER.1
drwxr-xr-x --- root root 4KiB 4KiB 42s source_vol/USER.2
rw-r--r-- --- root root 1KiB 4KiB 42s source_vol/USER.1/FILE_1
rw-r--r-- --- root root 1KiB 4KiB 42s source_vol/USER.1/FILE_2
rw-r--r-- --- root root 1KiB 4KiB 42s source_vol/USER.1/FILE_3
rw-r--r-- --- root root 1KiB 4KiB 42ssource_vol/USER.1/FILE_4
rw-r--r-- --- root root 1KiB 4KiB 42s source_vol/USER.1/FILE_5
rw-r--r-- --- root root 1KiB 4KiB 42s source_vol/USER.2/FILE_1
rw-r--r-- --- root root 1KiB 4KiB 42s source_vol/USER.2/FILE_5
rw-r--r-- --- root root 1KiB 4KiB 42s source_vol/USER.2/FILE_2
rw-r--r-- --- root root 1KiB 4KiB 42s source_vol/USER.2/FILE_3
rw-r--r-- --- root root 1KiB 4KiB 42s source_vol/USER.2/FILE_4
Xcp command : xcp scan -l <IP address or hostname of NFS server>:/source_vol
13 scanned, 0 matched, 0 error
Speed : 3.73 KiB in (4.89 KiB/s), 756 out (989/s)
Total Time : 0s.
STATUS : PASSED
----
====


== digitalização -q

Utilize o `-q` parâmetro com o `scan` comando para mostrar o número de ficheiros lidos.

.Sintaxe
[source, cli]
----
xcp scan -q <ip_address_or_hostname>:/source_vol
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -q <IP address or hostname of NFSserver>:/source_vol

Xcp command : xcp scan -q <IP address or hostname of NFS server>:/source_vol
13 scanned, 0 matched, 0 error
Speed : 3.73 KiB in (3.96 KiB/s), 756 out(801/s)
Total Time : 0s.
STATUS : PASSED
----
====


== scan -stats, scan -csv e scan -html

Use os `-stats` parâmetros , `-csv` e `-html` com o `scan` comando para listar arquivos no formato de relatório estatístico de árvore.


NOTE: Os relatórios XCP (.csv, .html) são salvos no local do catálogo especificado no `xcp.ini` arquivo. Os arquivos são armazenados na `<catalog path>/catalog/indexes/1/reports` pasta. Você pode exibir relatórios de exemplo no apêndice.

.Sintaxe
[source, cli]
----
xcp scan -stats <ip_address>:/source_vol
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
root@client1 linux]# ./xcp scan -stats <ip_address>:/fg1

Job ID: Job_2023-11-23_23.23.33.930501_scan
== Maximum Values ==
Size Used Depth File Path Namelen Dirsize
50.4 MiB 50.6 MiB 1 24 20 33
== Average Values ==
Size Depth Namelen Dirsize
15.3 MiB 0 6 33
== Top Space Users ==
root
107 MiB
== Top File Owners ==
root
34
== Top File Extensions ==
.sh .out .py .sh1 other
8 2 2 1 20
16.0 KiB 3.09 MiB 448 1.48 KiB 502 MiB
== Number of files ==
empty <8KiB 8-64KiB 64KiB-1MiB 1-10MiB 10-100MiB >100MiB
20 1 2 10
== Space used ==
empty <8KiB 8-64KiB 64KiB-1MiB 1-10MiB 10-100MiB >100MiB
76 KiB 12 KiB 5.16 MiB 102 MiB
== Directory entries ==
empty 1-10 10-100 100-1K 1K-10K >10K

== Depth ==
0-5 6-10 11-15 16-20 21-100 >100
34
== Accessed ==
>1 year9-12 months 6-9 months 3-6 months 1-3 months 1-31 days 1-24 hrs <1 hour <15 mins
future
33
505 MiB
== Modified ==
>1 year9-12 months 6-9 months 3-6 months 1-3 months 1-31 days 1-24 hrs <1 hour <15 mins
future
16
17
400 MiB 105
MiB
== Changed ==
>1 year9-12 months 6-9 months 3-6 months 1-3 months 1-31 days 1-24 hrs <1 hour <15 mins
future
16
17
400 MiB 105
MiB
== Path ==
0-1024 >1024
33
Total count: 34
Directories: 1
Regular files: 33
Symbolic links: None
Special files: None
Hard links: None
Multilink files: None
Space Saved by Hard links (KB): 0
Sparse data: N/A
Dedupe estimate: N/A
Total space for regular files: size: 505 MiB, used: 107 MiB
Total space for symlinks: size: 0, used: 0
Total space for directories: size: 8 KiB, used: 8 KiB
Total space used: 107 MiB
Xcp command : xcp scan -stats <ip_address>:/fg1
Stats : 34 scanned
Speed : 6.35 KiB in (7.23 KiB/s), 444 out (506/s)
Total Time : 0s.
Job ID : Job_2023-11-23_23.23.33.930501_scan
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/
Job_2023-11-23_23.23.33.930501_scan.log

STATUS : PASSED
[root@client 1 linux]#


----
====
.Sintaxe
[source, cli]
----
xcp scan -csv <ip_address_or_hostname>:/source_vol
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
root@localhost linux]# ./xcp scan -csv <IP address or hostname of NFS server>:/source_vol

scan <IP address or hostname of NFS server>:/source_vol
options,"{'-csv': True}"
summary,"13 scanned, 3.73 KiB in (11.3 KiB/s), 756 out (2.23 KiB/s), 0s."
Maximum Values,Size,Used,Depth,Namelen,Dirsize
Maximum Values,1024,4096,2,10,5
Average Values,Namelen,Size,Depth,Dirsize
Average Values,6,1024,1,4
Top Space Users,root
Top Space Users,53248
Top File Owners,root
Top File Owners,13
Top File Extensions,other
Top File Extensions,10
Number of files,empty,<8KiB,8-64KiB,64KiB-1MiB,1-10MiB,10-100MiB,>100MiB
Number of files,0,10,0,0,0,0,0
Space used,empty,<8KiB,8-64KiB,64KiB-1MiB,1-10MiB,10-100MiB,>100MiB
Space used,0,40960,0,0,0,0,0
Directory entries,empty,1-10,10-100,100-1K,1K-10K,>10K
Directory entries,0,3,0,0,0,0
Depth,0-5,6-10,11-15,16-20,21-100,>100
Depth,13,0,0,0,0,0
Accessed,>1 year,>1 month,1-31 days,1-24 hrs,<1 hour,<15 mins,future
Accessed,0,0,0,0,0,10,0
Modified,>1 year,>1 month,1-31 days,1-24 hrs,<1 hour,<15 mins,future
Modified,0,0,0,0,0,10,0
Changed,>1 year,>1 month,1-31 days,1-24 hrs,<1 hour,<15 mins,future
Changed,0,0,0,0,0,10,0

Total count,13
Directories,3
Regular files,10
Symbolic links,0
Special files,0
Hard links,0,
multilink files,0,
Space Saved by Hard links (KB),0
Sparse data,N/A
Dedupe estimate,N/A
Total space for regular files,size,10240,used,40960
Total space for symlinks,size,0,used,0
Total space for directories,size,12288,used,12288
Total space used,53248
Xcp command : xcp scan -csv <IP address or hostname of NFS server>:/source_vol
13 scanned, 0 matched, 0 error
Speed : 3.73 KiB in (11.2 KiB/s), 756 out (2.22 KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====
.Sintaxe
[source, cli]
----
xcp scan -html <ip_address_or_hostname>:/source_vol
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
root@localhost linux]# ./xcp scan -html <IP address or hostname of NFS server>:/source_vol

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<html><head>
[redacted HTML contents]
</body></html>
Xcp command : xcp scan -html <IP address or hostname of NFSserver>:/source_vol
13 scanned, 0 matched, 0 error
Speed : 3.73 KiB in (4.31 KiB/s), 756 out(873/s)
Total Time : 0s.
STATUS : PASSED
[root@localhost source_vol]#
----
====


== scan -não-nomes

Use o `-nonames` parâmetro com o `scan` comando para excluir nomes de usuários e grupos de listas de arquivos ou relatórios.


NOTE: Quando usado com o `scan` comando, o `-nonames` parâmetro só se aplica a listas de arquivos retornadas usando a `-l` opção.

.Sintaxe
[source, cli]
----
xcp scan -nonames <ip_address_or_hostname>:/source_vol
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -nonames <IP address or hostname of NFS server>:/source_vol

source_vol
source_vol/USER.1
source_vol/USER.2
source_vol/USER.1/FILE_1
source_vol/USER.1/FILE_2
source_vol/USER.1/FILE_3
source_vol/USER.1/FILE_4
source_vol/USER.1/FILE_5
source_vol/USER.2/FILE_1
source_vol/USER.2/FILE_5
source_vol/USER.2/FILE_2
source_vol/USER.2/FILE_3
source_vol/USER.2/FILE_4
Xcp command : xcp scan -nonames <IP address or hostname of NFSserver>:/source_vol
13 scanned, 0 matched, 0 error
Speed : 3.73 KiB in (4.66 KiB/s), 756 out(944/s)
Total Time : 0s.
STATUS : PASSED
----
====


== scan -newid <name>

Use o `-newid <name>` parâmetro com o `scan` comando para especificar o nome do catálogo para um novo índice ao executar uma digitalização.

.Sintaxe
[source, cli]
----
xcp scan -newid <name> <ip_address_or_hostname>:/source_vol
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -newid ID001 <IP address or hostname of NFS server>:/source_vol

Xcp command : xcp scan -newid ID001 <IP address or hostname of NFS server>:/source_vol
13 scanned, 0 matched, 0 error
Speed : 13.8 KiB in (17.7 KiB/s), 53.1 KiB out (68.0 KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====


== scan -id <catalog_name>

Use o `-id` parâmetro com o `scan` comando para especificar o nome do catálogo da cópia anterior ou índice de digitalização.

.Sintaxe
[source, cli]
----
xcp scan -id <catalog_name>
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -id 3

xcp: Index: {source: 10.10.1.10:/vol/ex_s01/etc/keymgr, target: None}
keymgr/root/cacert.pem
keymgr/cert/secureadmin.pem
keymgr/key/secureadmin.pem
keymgr/csr/secureadmin.pem
keymgr/root
keymgr/csr
keymgr/key
keymgr/cert
keymgr
9 reviewed, 11.4 KiB in (11.7 KiB/s), 1.33 KiB out (1.37 KiB/s), 0s.
----
====


== scan -match <filter>

Use o `-match <filter>` parâmetro com o `scan` comando para especificar que somente os arquivos e diretórios que correspondem a um filtro são processados.

.Sintaxe
[source, cli]
----
xcp scan -match <filter> <ip_address_or_hostname>:/source_vol
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
root@localhost linux]# ./xcp scan -match bin <IP address or hostname of NFS server>:/source_vol

source_vol
source_vol/USER.1/FILE_1
source_vol/USER.1/FILE_2
source_vol/USER.1/FILE_3
source_vol/USER.1/FILE_4
source_vol/USER.1/FILE_5
source_vol/USER.1/file1.txt
source_vol/USER.1/file2.txt
source_vol/USER.1/logfile.txt
source_vol/USER.1/log1.txt
source_vol/r1.txt
source_vol/USER.1
source_vol/USER.2
source_vol/USER.2/FILE_1
source_vol/USER.2/FILE_5
source_vol/USER.2/FILE_2
source_vol/USER.2/FILE_3
source_vol/USER.2/FILE_4
Filtered: 0 did not match
Xcp command : xcp scan -match bin <IP address or hostname of NFSserver>:/source_vol
18 scanned, 18 matched, 0 error
Speed : 4.59 KiB in (6.94 KiB/s), 756 out (1.12KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====


== scan -fmt <string_expression>

Use o `-fmt` parâmetro com o `scan` comando para especificar que somente arquivos e diretórios que correspondem ao formato especificado são retornados.

.Sintaxe
[source, cli]
----
xcp scan -fmt <string_expression> <ip_address_or_hostname>:/source_vol
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -fmt "'{}, {}, {}, {}, {}'.format(name, x, ctime, atime, mtime)"
<IP address or hostname of NFS server>:/source_vol

source_vol, <IP address or hostname of NFS server>:/source_vol, 1583294484.46, 1583294492.63,
1583294484.46
ILE_1, <IP address or hostname of NFS server>:/source_vol/USER.1/FILE_1, 1583293637.88,
1583293637.83, 1583293637.83
FILE_2, <IP address or hostname of NFS server>:/source_vol/USER.1/FILE_2, 1583293637.88,
1583293637.83, 1583293637.84
FILE_3, <IP address or hostname of NFS server>:/source_vol/USER.1/FILE_3, 1583293637.88,
1583293637.84, 1583293637.84
FILE_4, <IP address or hostname of NFS server>:/source_vol/USER.1/FILE_4, 1583293637.88,
1583293637.84, 1583293637.84
FILE_5, <IP address or hostname of NFS server>:/source_vol/USER.1/FILE_5, 1583293637.88,
1583293637.84, 1583293637.84
file1.txt, <IP address or hostname of NFS server>:/source_vol/USER.1/file1.txt, 1583294284.78,
1583294284.78, 1583294284.78
file2.txt, <IP address or hostname of NFS server>:/source_vol/USER.1/file2.txt, 1583294284.78,
1583294284.78, 1583294284.78
logfile.txt, <IP address or hostname of NFS server>:/source_vol/USER.1/logfile.txt,
1583294295.79, 1583294295.79, 1583294295.79
log1.txt, <IP address or hostname of NFS server>:/source_vol/USER.1/log1.txt, 1583294295.8,
1583294295.8, 1583294295.8
r1.txt, <IP address or hostname of NFS server>:/source_vol/r1.txt, 1583294484.46, 1583294484.45,
1583294484.45
USER.1, <IP address or hostname of NFS server>:/source_vol/USER.1, 1583294295.8, 1583294492.63,
1583294295.8
USER.2, <IP address or hostname of NFS server>:/source_vol/USER.2, 1583293637.95, 1583294492.63,
1583293637.95
FILE_1, <IP address or hostname of NFS server>:/source_vol/USER.2/FILE_1, 1583293637.95,
1583293637.94, 1583293637.94
FILE_5, <IP address or hostname of NFS server>:/source_vol/USER.2/FILE_5, 1583293637.96,
1583293637.94, 1583293637.94
FILE_2, <IP address or hostname of NFS server>:/source_vol/USER.2/FILE_2, 1583293637.96,
1583293637.95, 1583293637.95
FILE_3, <IP address or hostname of NFS server>:/source_vol/USER.2/FILE_3, 1583293637.96,
1583293637.95, 1583293637.95
FILE_4, <IP address or hostname of NFS server>:/source_vol/USER.2/FILE_4, 1583293637.96,
1583293637.95, 1583293637.96
Xcp command : xcp scan -fmt '{}, {}, {}, {}, {}'.format(name, x, ctime, atime, mtime) <IP address
or hostname of NFS server>:/source_vol
18 scanned, 0 matched, 0 error
Speed : 4.59 KiB in (4.14 KiB/s), 756 out (683/s)
Total Time : 1s.
STATUS : PASSED
----
====


== digitalização -du

Use o `-du` parâmetro com o `scan` comando para resumir o uso de espaço de cada diretório, incluindo subdiretórios.

.Sintaxe
[source, cli]
----
xcp scan -du <ip_address_or_hostname>:/source_vol
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -du <IP address or hostname of NFSserver>:/source_vol

24KiB source_vol/USER.1
24KiB source_vol/USER.2
52KiB source_vol
Xcp command : xcp scan -du <IP address or hostname of NFSserver>:/source_vol
18 scanned, 0 matched, 0 error
Speed : 4.59 KiB in (12.9 KiB/s), 756 out (2.07KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====


== digitalização -md5 <string_expression>

Use o `-md5` parâmetro com o `scan` comando para gerar somas de verificação para as listas de arquivos e salvar as somas de verificação ao indexar. O valor padrão é definido como false.


NOTE: As somas de verificação não são utilizadas para verificação de ficheiros; são utilizadas apenas para listas de ficheiros durante operações de leitura.

.Sintaxe
[source, cli]
----
xcp scan -md5 <ip_address_or_hostname>:/source_vol
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
root@localhost linux]# ./xcp scan -md5 <IP address or hostname of NFSserver>:/source_vol

source_vol
d47b127bc2de2d687ddc82dac354c415 source_vol/USER.1/FILE_1
d47b127bc2de2d687ddc82dac354c415 source_vol/USER.1/FILE_2
d47b127bc2de2d687ddc82dac354c415 source_vol/USER.1/FILE_3
d47b127bc2de2d687ddc82dac354c415 source_vol/USER.1/FILE_4
d47b127bc2de2d687ddc82dac354c415 source_vol/USER.1/FILE_5
d41d8cd98f00b204e9800998ecf8427e source_vol/USER.1/file1.txt
d41d8cd98f00b204e9800998ecf8427e source_vol/USER.1/file2.txt
d41d8cd98f00b204e9800998ecf8427esource_vol/USER.1/logfile.txt
d41d8cd98f00b204e9800998ecf8427e source_vol/USER.1/log1.txt
e894f2344aaa92289fb57bc8f597ffa9 source_vol/r1.txt
source_vol/USER.1
source_vol/USER.2
d47b127bc2de2d687ddc82dac354c415 source_vol/USER.2/FILE_1
d47b127bc2de2d687ddc82dac354c415 source_vol/USER.2/FILE_5
d47b127bc2de2d687ddc82dac354c415 source_vol/USER.2/FILE_2
d47b127bc2de2d687ddc82dac354c415 source_vol/USER.2/FILE_3
d47b127bc2de2d687ddc82dac354c415 source_vol/USER.2/FILE_4
Xcp command : xcp scan -md5 <IP address or hostname of NFS server>:/source_vol
18 scanned, 0 matched, 0 error
Speed : 16.0 KiB in (34.5 KiB/s), 2.29 KiB out (4.92 KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====


== scan -depth <n> (exame - profundidade)

Utilize o `-depth <n>` parâmetro com o `scan` comando para limitar a profundidade de pesquisa de um exame. O `-depth <n>` parâmetro especifica a profundidade nos subdiretórios que o XCP pode digitalizar arquivos. Por exemplo, se o número 2 for especificado, o XCP irá analisar apenas os dois primeiros níveis de subdiretório.

.Sintaxe
[source, cli]
----
xcp scan -depth <n> <ip_address_or_hostname>:/source_vol
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -depth 2 <IP address or hostname of NFS server>:/source_vol

source_vol
source_vol/r1.txt
source_vol/USER.1
source_vol/USER.2
source_vol/USER.1/FILE_1
source_vol/USER.1/FILE_2
source_vol/USER.1/FILE_3
source_vol/USER.1/FILE_4
source_vol/USER.1/FILE_5
source_vol/USER.1/file1.txt
source_vol/USER.1/file2.txt
source_vol/USER.1/logfile.txt
source_vol/USER.1/log1.txt
source_vol/USER.2/FILE_1
source_vol/USER.2/FILE_5
source_vol/USER.2/FILE_2
source_vol/USER.2/FILE_3
source_vol/USER.2/FILE_4
Xcp command : xcp scan -depth 2 <IP address or hostname of NFSserver>:/source_vol
18 scanned, 0 matched, 0 error
Speed : 4.59 KiB in (6.94 KiB/s), 756 out (1.12KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====


== scan -dircount <n[k]>

Use o `-dircount <n[k]>` parâmetro com o `scan` comando para especificar o tamanho da solicitação ao ler diretórios em uma varredura. O valor padrão é 64k.

.Sintaxe
[source, cli]
----
xcp scan -dircount <n[k]> <ip_address_or_hostname>:/source_vol
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -dircount 64k <IP address or hostname of NFS server>:/source_vol

source_vol
source_vol/USER.1/FILE_1
source_vol/USER.1/FILE_2
source_vol/USER.1/FILE_3
source_vol/USER.1/FILE_4
source_vol/USER.1/FILE_5
source_vol/USER.1/file1.txt
source_vol/USER.1/file2.txt
source_vol/USER.1/logfile.txt
source_vol/USER.1/log1.txt
source_vol/r1.txt
source_vol/USER.1
source_vol/USER.2
source_vol/USER.2/FILE_1
source_vol/USER.2/FILE_5
----
====


== digitalização -edupe

Use o `-edupe` parâmetro com o `scan` comando para incluir a estimativa de deduplicação nos relatórios.


NOTE: O Simple Storage Service (S3) não suporta arquivos esparsos. Portanto, especificar um bucket S3 como destino de destino `scan -edupe` retorna o valor "nenhum" para dados esparsos.

.Sintaxe
[source, cli]
----
xcp scan -edupe <ip_address_or_hostname>:/source_vol
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
root@localhost linux]# ./xcp scan -edupe <IP address or hostname of NFSserver>:/source_vol

== Maximum Values ==
Size Used Depth Namelen Dirsize
1 KiB 4 KiB 2 11 9
== Average Values ==
Namelen Size Depth Dirsize
6 682 1 5
== Top Space Users ==
root
52 KiB
== Top File Owners ==
root
18
== Top File Extensions ==
.txt other
5 10
== Number of files ==
empty <8KiB 8-64KiB 64KiB-1MiB 1-10MiB 10-100MiB >100MiB
    4 11
== Space used ==
empty <8KiB 8-64KiB 64KiB-1MiB 1-10MiB 10-100MiB >100MiB
40 KiB
== Directory entries ==
empty 1-10 10-100 100-1K 1K-10K >10K
3
== Depth ==
0-5 6-10 11-15 16-20 21-100 >100
18
== Accessed ==
>1 year >1 month 1-31 days 1-24 hrs <1 hour
4
<15 mins
11
future
== Modified ==
>1 year >1 month 1-31 days 1-24 hrs <1 hour <15 mins future
15
== Changed ==
>1 year >1 month 1-31 days 1-24 hrs <1 hour <15 mins future
                                     15
Total count: 18
Directories: 3
Regular files: 15
Symbolic links: None
Special files: None
Hard links: None,
multilink files: None,
Space Saved by Hard links (KB): 0
Sparse data: None
Dedupe estimate: N/A
Total space for regular files: size: 10.0 KiB, used: 40 KiB
Total space for symlinks: size: 0, used: 0
Total space for directories: size: 12 KiB, used: 12 KiB
Total space used: 52 KiB
Xcp command : xcp scan -edupe <IP address or hostname of NFSserver>:/source_vol
18 scanned, 0 matched, 0 error
Speed : 16.0 KiB in (52.7 KiB/s), 2.29 KiB out (7.52 KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====


== scan -bs <n[k]>

Use o `-bs <n[k]>` parâmetro com o `scan` comando para especificar o tamanho do bloco de leitura/gravação. Isto aplica-se a digitalizações que leem dados utilizando os `-md5` parâmetros ou `-edupe`. O tamanho padrão do bloco é 64k.

.Sintaxe
[source, cli]
----
xcp scan -bs <n[k]> <ip_address_or_hostname>:/source_vol
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -bs 32 <IP address or hostname of NFS server>:/source_vol

source_vol
source_vol/r1.txt
source_vol/USER.1
source_vol/USER.2
source_vol/USER.1/FILE_1
source_vol/USER.1/FILE_2
source_vol/USER.1/FILE_3
source_vol/USER.1/FILE_4
source_vol/USER.1/FILE_5
source_vol/USER.1/file1.txt
source_vol/USER.1/file2.txt
source_vol/USER.1/logfile.txt
source_vol/USER.1/log1.txt
source_vol/USER.2/FILE_1
source_vol/USER.2/FILE_5
source_vol/USER.2/FILE_2
source_vol/USER.2/FILE_3
source_vol/USER.2/FILE_4
Xcp command : xcp scan -bs 32 <IP address or hostname of NFSserver>:/source_vol
18 scanned, 0 matched, 0 error
Speed : 4.59 KiB in (19.0 KiB/s), 756 out (3.06KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====


== scan -parallel <n>

Use o `-parallel` parâmetro com o `scan` comando para especificar o número máximo de processos em lote simultâneos. O valor padrão é 7.

.Sintaxe
[source, cli]
----
xcp scan -parallel <n> <ip_address_or_hostname>:/source_vol
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -parallel 5 <IP address or hostname of NFS server>:/source_vol

source_vol
source_vol/USER.1/FILE_1
source_vol/USER.1/FILE_2
source_vol/USER.1/FILE_3
source_vol/USER.1/FILE_4
source_vol/USER.1/FILE_5
source_vol/USER.1/file1.txt
source_vol/USER.1/file2.txt
source_vol/USER.1/logfile.txt
source_vol/USER.1/log1.txt
source_vol/r1.txt
source_vol/USER.1
source_vol/USER.2
source_vol/USER.2/FILE_1
source_vol/USER.2/FILE_5
source_vol/USER.2/FILE_2
source_vol/USER.2/FILE_3
source_vol/USER.2/FILE_4
Xcp command : xcp scan -parallel 5 <IP address or hostname of NFS server>:/source_vol
18 scanned, 0 matched, 0 error
Speed : 4.59 KiB in (7.36 KiB/s), 756 out (1.19 KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====


== Scan -noid

Use o `-noId` parâmetro com o `scan` comando para desativar a criação de um índice padrão. O valor padrão é false.

.Sintaxe
[source, cli]
----
xcp scan -noId <ip_address_or_hostname>:/source_vol
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -noId <IP address or hostname of NFS server>:/source_vol

source_vol
source_vol/USER.1/FILE_1
source_vol/USER.1/FILE_2
source_vol/USER.1/FILE_3
source_vol/USER.1/FILE_4
source_vol/USER.1/FILE_5
source_vol/USER.1/file1.txt
source_vol/USER.1/file2.txt
source_vol/USER.1/logfile.txt
source_vol/USER.1/log1.txt
source_vol/r1.txt
source_vol/USER.1
source_vol/USER.2
source_vol/USER.2/FILE_1
source_vol/USER.2/FILE_5
source_vol/USER.2/FILE_2
source_vol/USER.2/FILE_3
source_vol/USER.2/FILE_4
Xcp command : xcp scan -noId <IP address or hostname of NFSserver>:/source_vol
18 scanned, 0 matched, 0 error
Speed : 4.59 KiB in (5.84 KiB/s), 756 out(963/s)
Total Time : 0s.
STATUS : PASSED
----
====


== scan -subdir-namentos

Use o `-subdir-names` parâmetro com o `scan` comando para recuperar os nomes dos subdiretórios de nível superior em um diretório.

.Sintaxe
[source, cli]
----
xcp scan -subdir-names <ip_address_or_hostname>:/source_vol
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -subdir-names <IP address or hostname of NFS server>:/source_vol

source_vol
Xcp command : xcp scan -subdir-names <IP address or hostname of NFS server>:/source_vol
7 scanned, 0 matched, 0 error
Speed : 1.30 KiB in (1.21 KiB/s), 444 out(414/s)
Total Time : 1s.
STATUS : PASSED
----
====


== digitalização -preservar-tempo

Use o `-preserve-atime` parâmetro com o `scan` comando para restaurar todos os arquivos para a última data acessada na origem.

Quando um compartilhamento NFS é verificado, o tempo de acesso é modificado nos arquivos se o sistema de armazenamento estiver configurado para modificar o tempo de acesso na leitura. O XCP não altera diretamente o tempo de acesso. O XCP lê os ficheiros um a um e isto aciona uma atualização para o tempo de acesso. A `-preserve-atime` opção repõe o tempo de acesso ao valor original definido antes da operação de leitura do XCP.

.Sintaxe
[source, cli]
----
xcp scan -preserve-atime <ip_address_or_hostname>:/source_vol
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
[root@client 1 linux]# ./xcp scan -preserve-atime 101.10.10.10:/source_vol

xcp: Job ID: Job_2022-06-30_14.14.15.334173_scan
source_vol/USER2/DIR1_4/FILE_DIR1_4_1024_1
source_vol/USER2/DIR1_4/FILE_DIR1_4_13926_4
source_vol/USER2/DIR1_4/FILE_DIR1_4_65536_2
source_vol/USER2/DIR1_4/FILE_DIR1_4_7475_3
source_vol/USER2/DIR1_4/FILE_DIR1_4_20377_5
source_vol/USER2/DIR1_4/FILE_DIR1_4_26828_6
source_vol/USER2/DIR1_4/FILE_DIR1_4_33279_7
source_vol/USER2/DIR1_4/FILE_DIR1_4_39730_8
source_vol/USER1
source_vol/USER2
source_vol/USER1/FILE_USER1_1024_1
source_vol/USER1/FILE_USER1_65536_2
source_vol/USER1/FILE_USER1_7475_3
source_vol/USER1/FILE_USER1_13926_4
source_vol/USER1/FILE_USER1_20377_5
source_vol/USER1/FILE_USER1_26828_6
source_vol/USER1/FILE_USER1_33279_7
source_vol/USER1/FILE_USER1_39730_8
source_vol/USER1/DIR1_2
source_vol/USER1/DIR1_3
source_vol/USER2/FILE_USER2_1024_1
source_vol/USER2/FILE_USER2_65536_2
source_vol/USER2/FILE_USER2_7475_3
source_vol/USER2/FILE_USER2_13926_4
source_vol/USER2/FILE_USER2_20377_5
source_vol/USER2/FILE_USER2_26828_6
source_vol/USER2/FILE_USER2_33279_7
source_vol/USER2/FILE_USER2_39730_8
source_vol/USER2/DIR1_3
source_vol/USER2/DIR1_4
source_vol/USER1/DIR1_2/FILE_DIR1_2_1024_1
source_vol/USER1/DIR1_2/FILE_DIR1_2_7475_3
source_vol/USER1/DIR1_2/FILE_DIR1_2_33279_7
source_vol/USER1/DIR1_2/FILE_DIR1_2_26828_6
source_vol/USER1/DIR1_2/FILE_DIR1_2_65536_2
source_vol/USER1/DIR1_2/FILE_DIR1_2_39730_8
source_vol/USER1/DIR1_2/FILE_DIR1_2_13926_4
source_vol/USER1/DIR1_2/FILE_DIR1_2_20377_5
source_vol/USER1/DIR1_3/FILE_DIR1_3_1024_1
source_vol/USER1/DIR1_3/FILE_DIR1_3_7475_3
source_vol/USER1/DIR1_3/FILE_DIR1_3_65536_2
source_vol/USER1/DIR1_3/FILE_DIR1_3_13926_4
source_vol/USER1/DIR1_3/FILE_DIR1_3_20377_5
source_vol/USER1/DIR1_3/FILE_DIR1_3_26828_6
source_vol/USER1/DIR1_3/FILE_DIR1_3_33279_7
source_vol/USER1/DIR1_3/FILE_DIR1_3_39730_8
source_vol/USER2/DIR1_3/FILE_DIR1_3_1024_1
source_vol/USER2/DIR1_3/FILE_DIR1_3_65536_2
source_vol/USER2/DIR1_3/FILE_DIR1_3_7475_3
source_vol/USER2/DIR1_3/FILE_DIR1_3_13926_4
source_vol/USER2/DIR1_3/FILE_DIR1_3_20377_5
source_vol/USER2/DIR1_3/FILE_DIR1_3_26828_6
source_vol/USER2/DIR1_3/FILE_DIR1_3_33279_7
source_vol/USER2/DIR1_3/FILE_DIR1_3_39730_8
source_vol
Xcp command : xcp scan -preserve-atime 101.10.10.10:/source_vol
Stats : 55 scanned
Speed : 14.1 KiB in (21.2 KiB/s), 2.33 KiB out (3.51 KiB/s)
Total Time : 0s.
Job ID : Job_2022-06-30_14.14.15.334173_scan
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2022-06-30_14.14.15.334173_scan.log
STATUS : PASSED
----
====


== digitalização -s3.insecure

Use o `-s3.insecure` parâmetro com o `scan` comando para usar HTTP em vez de HTTPS para comunicação de bucket S3.

.Sintaxe
[source, cli]
----
xcp scan -s3.insecure s3://<bucket_name>
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp scan -s3.insecure s3://bucket1

Job ID: Job_2023-06-08_08.16.31.345201_scan
file5g_1
USER1/FILE_USER1_1024_1
USER1/FILE_USER1_1024_2
USER1/FILE_USER1_1024_3
USER1/FILE_USER1_1024_4
USER1/FILE_USER1_1024_5
Xcp command : xcp scan -s3.insecure s3:// -bucket1
Stats : 8 scanned, 6 s3.objects
Speed : 0 in (0/s), 0 out (0/s)
Total Time : 2s.
Job ID : Job_2023-06-08_08.16.31.345201_scan
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-06-08_08.16.31.345201_scan.log
STATUS : PASSED
----
====


== scan -s3.endpoint <s3_endpoint_url>

Use o `-s3.endpoint <s3_endpoint_url>` parâmetro com o `scan` comando para substituir o URL de endpoint padrão da AWS com um URL especificado para a comunicação de bucket do S3.

.Sintaxe
[source, cli]
----
xcp scan -s3.endpoint https://<endpoint_url>: s3://<bucket_name>
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp scan -s3.endpoint https://<endpoint_url>: s3://xcp-testing

Job ID: Job_2023-06-13_11.23.06.029137_scan
aws_files/USER1/FILE_USER1_1024_1
aws_files/USER1/FILE_USER1_1024_2
aws_files/USER1/FILE_USER1_1024_3
aws_files/USER1/FILE_USER1_1024_4
aws_files/USER1/FILE_USER1_1024_5
Xcp command : xcp scan -s3.endpoint https://<endpoint_url>: s3://xcp-testing
Stats : 8 scanned, 5 s3.objects
Speed : 0 in (0/s), 0 out (0/s)
Total Time : 0s.
Job ID : Job_2023-06-13_11.23.06.029137_scan
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-06-13_11.23.06.029137_scan.log
STATUS : PASSED
----
====


== digitalização -s3.profile <name>

Use o `s3.profile` parâmetro com o `scan` comando para especificar um perfil do arquivo de credenciais da AWS para comunicação de bucket do S3.

.Sintaxe
[source, cli]
----
xcp scan -s3.profile <name> -s3.endpoint https://<endpoint_url>: s3://<bucket_name>
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp scan -s3.profile sg -s3.endpoint https://<endpoint_url>:
s3://bucket1

Job ID: Job_2023-06-08_08.47.11.963479_scan
1 scanned, 0 in (0/s), 0 out (0/s), 5s
USER1/FILE_USER1_1024_1
USER1/FILE_USER1_1024_2
USER1/FILE_USER1_1024_3
USER1/FILE_USER1_1024_4
USER1/FILE_USER1_1024_5
Xcp command : xcp scan -s3.profile sg -s3.endpoint https://<endpoint_url>: s3://bucket1
Stats : 7 scanned, 5 s3.objects
Speed : 0 in (0/s), 0 out (0/s)
Total Time : 6s.
Job ID : Job_2023-06-08_08.47.11.963479_scan
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-06-08_08.47.11.963479_scan.log
STATUS : PASSED
[root@client1 linux]#
----
====


== digitalização -s3.noverify

Use o `-s3.noverify` parâmetro com o `scan` comando para substituir a verificação padrão da certificação SSL para comunicação de bucket S3.

.Sintaxe
[source, cli]
----
xcp scan -s3.noverify s3://<bucket_name>
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
root@client1 linux]# ./xcp scan -s3.noverify s3:// bucket1

Job ID: Job_2023-06-13_11.00.59.742237_scan
aws_files/USER1/FILE_USER1_1024_1
aws_files/USER1/FILE_USER1_1024_2
aws_files/USER1/FILE_USER1_1024_3
aws_files/USER1/FILE_USER1_1024_4
aws_files/USER1/FILE_USER1_1024_5
Xcp command : xcp scan -s3.noverify s3://bucket1
Stats : 8 scanned, 5 s3.objects
Speed : 0 in (0/s), 0 out (0/s)
Total Time : 2s.
Job ID : Job_2023-06-13_11.00.59.742237_scan
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-06-13_11.00.59.742237_scan.log
STATUS : PASSED
----
====