---
sidebar: sidebar 
permalink: xcp-smb-reference-copy.html 
keywords: netapp, xcp, reference, smb, command, commands 
summary: 'Referência do comando "copy" do SMB do XCP' 
---
= cópia
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O `copy` comando verifica e copia toda a estrutura do diretório de origem para um compartilhamento SMB de destino. O `copy` comando requer caminhos de origem e destino como variáveis. Os arquivos digitalizados e copiados, a taxa de transferência/velocidade e os detalhes do tempo decorrido são impressos no console uma vez a cada cinco segundos.

[NOTE]
====
* O ficheiro de registo de tempo de execução é armazenado em "C: NetApp".
*  `copy`Este comando copia dados sem uma lista de controle de acesso (ACL).


====
.Sintaxe
[source, cli]
----
xcp copy \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp copy \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
317 scanned, 0 matched, 316 copied, 0 errors
Total Time : 2s
STATUS : PASSED
----
====
A tabela a seguir lista os `copy` parâmetros e sua descrição.

[cols="2*"]
|===
| Parâmetro | Descrição 


| <<smb_copy_help,copy -h, --help>> | Exibe informações detalhadas sobre o `copy` comando. 


| <<cópia -v>> | Aumente a verbosidade da depuração. 


| <<smb_copy_parallel,copiar -paralelo >> | Especifica o número de processos simultâneos (padrão: <cpu-count>). 


| <<smb_copy_match,copiar -corresponder >> | Processa apenas ficheiros e diretórios que correspondem ao filtro (consulte `xcp help - match` para obter detalhes). 


| <<smb_copy_exclude,copiar -excluir >> | Exclui apenas arquivos e diretórios no filtro 


| <<copiar -preservar-tempo>> | Restaura a última data acessada na origem. 


| <<smb_copy_acl,copiar -acl>> | Copia informações de segurança. 


| <<smb_copy_acl,copy -fallback-user >> | Especifica o usuário do ative Directory ou o usuário local (não domínio) na máquina de destino que recebe as permissões de usuários de máquina de origem local (não domínio). Por exemplo, domínio/administrador. 


| <<smb_copy_acl,copy -fallback-group >> | Especifica o grupo do ative Directory ou o grupo local (não domínio) na máquina de destino que recebe as permissões de grupos de máquinas de origem local (não domínio). Por exemplo, domínio/administradores. 


| <<smb_copy_root,copiar -root>> | Copia as ACLs de um diretório raiz. 


| <<smb_copy_aclverify,copy -aclverify (sim, não)>> | Fornece uma opção para ignorar ou incluir a verificação ACL durante a operação copy -acl. 


| <<copiar -nopropriedade>> | Não copia a propriedade. 


| <<smb_copy_bs,copiar -bs >> | Tamanho de bloqueio de leitura/escrita (predefinição:1M) 


| <<copiar -anúncios>> | Copia fluxos de dados alternativos NTFS do compartilhamento SMB de origem para o compartilhamento SMB de destino. 
|===


== copy -h, --help

Use os `-h` parâmetros e `–-help` com o `copy` comando para exibir informações detalhadas sobre o `copy` comando

.Sintaxe
[source, cli]
----
xcp copy –help
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
C:\netapp\xcp>xcp copy –help

usage: xcp copy [-h] [-v] [-parallel <n>] [-match <filter>] [-exclude <filter>] [-preserve- atime] [-acl] [-fallback-user FALLBACK_USER]
[-fallback-group FALLBACK_GROUP] [-loglevel <name>] [-root] [-noownership] [- aclverify {yes,no}] [-bs <n>] [-ads]
         source target

positional arguments:
   source
   target

optional arguments:
-h, --help            show this help message and exit
-v                    increase debug verbosity
-parallel <n>         number of concurrent processes (default: <cpu-count>)
-match <filter>       only process files and directories that match the filter (see `xcp help -match` for details)
-exclude <filter>     Exclude files and directories that match the filter (see `xcp help - exclude` for details)
-preserve-atime       restore last accessed date on source
-acl                  copy security information
-fallback-user FALLBACK_USER
                      the name of the user on the target machine to receive the permissions of local (non-domain) source machine users (eg. domain\administrator)
-fallback-group FALLBACK_GROUP
                      the name of the group on the target machine to receive the permissions of local (non-domain) source machine groups (eg. domain\administrators)
-loglevel <name>      option to set log level filter (default:INFO)
-root                 copy acl for root directory
-noownership          do not copy ownership
-aclverify {yes,no}   choose whether you need to skip acl verification
-bs <n>               read/write block size for copy (default: 1M)
-ads                  copy NTFS alternate data streams.
----
====


== cópia -v

Use o `-v` parâmetro com o `copy` comando para fornecer informações detalhadas de depuração.

.Sintaxe
[source, cli]
----
xcp copy -v \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy -v \\<IP address of SMB destination server>\src \\<IP address of SMB destination server>\dest\d1

failed to set attributes for "d1": (5, 'CreateDirectory', 'Access is denied.')
failed to copy "f1.txt": (5, 'CreateFile', 'Access is denied.')
failed to set attributes for "": (5, 'SetFileAttributesW', 'Access is denied.') error setting timestamps on "": errno (code: 5) Access is denied.
H:\p 4\xcp_latest\xcp_cifs\xcp\ main .py copy -v \\<IP address of SMB destination server>\src \\<IP address of SMB destination server>\dest\d1
3 scanned, 0 matched, 0 skipped, 1 copied, 0 (0/s), 3 errors
Total Time : 3s
STATUS : FAILED
----
====


== copy -parallel <n>

Use o `-parallel <n>` parâmetro com o `copy` comando para definir um número maior ou menor de processos simultâneos XCP. O valor padrão para `-parallel` é igual à contagem de CPU.


NOTE: O valor máximo para n é 61.

.Sintaxe
[source, cli]
----
xcp copy -parallel <n> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy -parallel 7	\\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp copy -parallel 7 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
317 scanned, 0 matched, 316 copied, 0errors
Total Time : 2s
STATUS : PASSED
----
====


== copiar - combinar <filter>

Use o `-match <filter>` parâmetro com o `copy` comando para copiar apenas os dados que correspondem ao argumento passado.

.Sintaxe
[source, cli]
----
xcp copy -match <filter> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy -match "'gx' in name" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp copy -match 'gx' in name \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
317 scanned, 5 matched, 4 copied, 0 errors
Total Time : 1s
STATUS : PASSED
----
====


== copiar - excluir <filter>

Use o `-exclude <filter>` parâmetro com o `copy` comando para copiar somente os dados excluídos.

.Sintaxe
[source, cli]
----
xcp copy -exclude <filter> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
No exemplo a seguir, os arquivos e diretórios que têm a string "ressync" em seu nome foram excluídos para cópia.

.Mostrar exemplo
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy -exclude "'resync' in name" \\<IP address or hostname of SMB server>\source_share \\<IP address or hostname of SMB server>\dest_share


xcp copy -exclude 'resync' in name \\<IP address or hostname of SMB server>\source_share \\\\<IP address or hostname of SMB server>\dest_share
18 scanned, 2 excluded, 0 skipped, 15 copied, 122KiB (50.5KiB/s), 0 errors
Total Time : 2s
STATUS : PASSED
----
====


== copiar -preservar-tempo

Use o `-preserve-atime` parâmetro com o `copy` comando para redefinir o "atime" para o valor original antes de XCP ler o arquivo.

.Sintaxe
[source, cli]
----
xcp copy -preserve-atime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy -preserve-atime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp copy -preserve-atime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
317 scanned, 0 matched, 316 copied, 0 errors
Total Time : 2s
STATUS : PASSED
----
====


== copy -acl -fallback-user <fallback_user> -fallback-group <fallback_group>

Use o `-acl` parâmetro com o `copy` comando para ativar a transferência dos descritores de segurança (ACLs).

Use o `-acl` parâmetro com `-fallback-user` as opções e `-fallback-group` para especificar um usuário e um grupo na máquina de destino ou do ative Directory para receber as permissões de usuários ou grupos de máquinas de origem locais (que não sejam de domínio). Isso não se refere a usuários não correspondidos de um ative Directory.

.Sintaxe
[source, cli]
----
xcp copy -acl -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----


== copy -aclverify (sim, não)

Use o `-aclverify {yes,no}` parâmetro com o `copy` comando para fornecer uma opção para ignorar ou incluir a verificação ACL durante uma operação de cópia ACL.

Você deve usar o `-aclverify {yes,no}` parâmetro com o `copy -acl` comando. Por padrão, a operação de cópia ACL verifica as ACLs. Se definir a `-aclverify` opção como `no`, pode ignorar a verificação da ACL e `fallback-user` as opções e `fallback-group` não são necessárias. Se definir `-aclverify` como `yes`, é necessário o `fallback-user` e `fallback-group` as opções, conforme apresentado no exemplo seguinte.

.Sintaxe
[source, cli]
----
xcp copy -acl -aclverify yes -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
C:\NetApp\xcp>xcp copy -acl -aclverify yes -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group"
\\<source_IP_address>\source_share \\<destination_IP_address>\dest_share

12 scanned, 0 matched, 0 skipped, 0 copied, 0 (0/s), 0 errors, 5s, 0 acls copied
12 scanned, 0 matched, 0 skipped, 0 copied, 0 (0/s), 0 errors, 10s, 0 acls copied
12 scanned, 0 matched, 0 skipped, 0 copied, 0 (0/s), 0 errors, 15s, 0 acls copied xcp copy -acl -aclverify yes -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share
12 scanned, 0 matched, 0 skipped, 11 copied, 10KiB (634/s), 0 errors, 11 acls copied
Total Time : 16s
STATUS : PASSED

C:\NetApp\xcp>xcp copy -acl -aclverify no \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share

xcp copy -acl -aclverify no \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share
12 scanned, 0 matched, 0 skipped, 11 copied, 10KiB (5.61KiB/s), 0 errors, 11 acls copied
Total Time : 1s
STATUS : PASSED
----
====


== copiar -root

Use o `-root` parâmetro com o `copy` comando para copiar as ACLs para o diretório raiz.

.Sintaxe
[source, cli]
----
xcp copy -acl -root -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
C:\NetApp\XCP>xcp copy -acl -root -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp copy -acl -root -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
6 scanned, 0 matched, 0 skipped, 5 copied, 200 (108/s), 0 errors, 6 acls copied
Total Time : 1s
STATUS : PASSED
----
====


== copiar -nopropriedade

Use o `-noownership` parâmetro com o `copy` comando para especificar para não copiar a propriedade da origem para o destino. Você deve usar `-noownership` com a `-acl` opção e ela requer `fallback-user` e `fallback-group` como parâmetros obrigatórios.

.Sintaxe
[source, cli]
----
xcp.exe copy -acl -noownership -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
C:\Netapp\xcp>xcp.exe copy -acl -noownership -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share

568 scanned, 0 matched, 0 skipped, 0 copied, 0 (0/s), 0 errors, 5s, 0 acls copied
568 scanned, 0 matched, 0 skipped, 0 copied, 0 (0/s), 0 errors, 10s, 0 acls copied
568 scanned, 0 matched, 0 skipped, 135 copied, 4.26MiB (872KiB/s), 0 errors, 15s, 137 acls copied xcp.exe copy -acl -noownership -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share
568 scanned, 0 matched, 0 skipped, 567 copied, 17.7MiB (1.01MiB/s), 0 errors, 567 acls copied
Total Time : 17s
STATUS : PASSED
----
====


== copy -bs <n>

Use o `-bs <n>` parâmetro com o `copy` comando para fornecer um tamanho de bloco de leitura/gravação. O valor padrão é 1M.

.Sintaxe
[source, cli]
----
xcp.exe copy -bs <n> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
c:\Netapp\xcp>xcp.exe copy -bs 32k \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share

xcp.exe copy -bs 32k \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share
568 scanned, 0 matched, 0 skipped, 567 copied, 17.7MiB (6.75MiB/s), 0 errors
Total Time : 2s
STATUS : PASSED
----
====


== copiar -anúncios

Use o `-ads` parâmetro com o `copy` comando para copiar fluxos de dados alternativos NTFS do compartilhamento SMB de origem para o compartilhamento SMB de destino.

.Sintaxe
[source, cli]
----
xcp copy -ads \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostrar exemplo
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy -ads \\<source_IP_address>\source_share\src \\<dest_IP_address>\dest_share

6   scanned, 0 matched, 0 skipped, 3 copied, 13 (2.41/s), 0 errors, 5s, 10 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	10s, 11 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	15s, 12 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	20s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	25s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	30s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	35s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	40s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	45s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	2m15s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	3m5s, 13 ads copied
xcp copy -ads \\<source_IP_address>\source_share\src \\<desination_IP_address>\dest_share
6 scanned, 0 matched, 0 skipped, 5 copied, 26 (0.137/s), 0 errors, 14 ads copied
Total Time : 3m9s
STATUS : PASSED
----
====